server:
  port: 8088
  tomcat:
    uri-encoding: utf-8


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ace?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
